### creating one dimentional numpy array(vector)

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [5]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

###  creating two dimentional numpy array(matrix)

In [7]:
b=np.array([1,2,3],[4,5,6])
b

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [8]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b=np.array([[1,2,3],[45678]])
b

C:\Users\amanr\AppData\Local\Temp\ipykernel_8196\1936815379.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[45678]])


array([list([1, 2, 3]), list([45678])], dtype=object)

In [10]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [12]:
np.array([1,0,3],dtype=float)

array([1., 0., 3.])

In [13]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
np.arange(10).reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [23]:
np.ones(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.random.rand(3,5)

array([[0.57605963, 0.35764106, 0.08350149, 0.73187945, 0.23605564],
       [0.8107206 , 0.45895057, 0.102114  , 0.70304821, 0.57767225],
       [0.83740394, 0.48771254, 0.60510528, 0.56434473, 0.75000764]])

In [28]:
np.random.randn(3,5)

array([[ 0.32919569,  0.14145553, -2.42311303, -0.75345583,  0.93942801],
       [ 0.93724584, -0.44172745,  0.36117516,  0.71189049, -0.20163299],
       [ 0.08435633,  0.8575069 , -0.08095527, -0.29680683, -0.97794196]])

In [30]:
np.random.randint(3,50)

24

In [31]:
np.linspace(0,3,6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [32]:
np.linspace(-3,3,6)

array([-3. , -1.8, -0.6,  0.6,  1.8,  3. ])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a2=np.arange(10,dtype=float)
a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
a2=a2.reshape(2,5)

In [40]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
a4=np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
a1.ndim

1

In [47]:
a2.ndim

2

In [48]:
a3.ndim

3

In [49]:
a1.shape

(10,)

In [51]:
a2.shape

(2, 5)

In [52]:
a3.shape

(2, 2, 2)

In [53]:
a4.shape

(3, 3, 3)

In [54]:
a1.size

10

In [55]:
a2.size

10

In [57]:
a3.size

8

In [58]:
a4.size

27

### changing data type

In [59]:
x=np.array([1.9,2.0,3.0])
x

array([1.9, 2. , 3. ])

In [60]:
x.astype(int)

array([1, 2, 3])

In [61]:
a=np.arange(14).reshape(2,7)

In [62]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [63]:
a+2

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15]])

In [64]:
a*2

array([[ 0,  2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24, 26]])

In [65]:
a-2

array([[-2, -1,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11]])

In [66]:
a/2

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ],
       [3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5]])

In [67]:
a**2

array([[  0,   1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144, 169]])

In [68]:
a//2

array([[0, 0, 1, 1, 2, 2, 3],
       [3, 4, 4, 5, 5, 6, 6]], dtype=int32)

In [69]:
a%2

array([[0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]], dtype=int32)

In [87]:
b=np.arange(14).reshape(2,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [78]:
b>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
b<2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
a+b

array([[ 0,  2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24, 26]])

In [89]:
a-b

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [90]:
a*b

array([[  0,   1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144, 169]])

In [91]:
a/b

C:\Users\amanr\AppData\Local\Temp\ipykernel_8196\1348051284.py:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [94]:
c=np.random.random((3,3))
c

array([[0.16763959, 0.01783673, 0.7258271 ],
       [0.60034984, 0.67189105, 0.78994551],
       [0.65377653, 0.26650131, 0.87976717]])

In [97]:
e=np.round(c*100)
e

array([[17.,  2., 73.],
       [60., 67., 79.],
       [65., 27., 88.]])

In [100]:
np.max(e)

88.0

In [101]:
np.min(e)

2.0

In [102]:
np.sum(a)

478.0

In [103]:
np.prod(a)

121734791006400.0

In [104]:
np.max(e,axis=1)

array([73., 79., 88.])

In [105]:
np.min(e,axis=1)

array([ 2., 60., 27.])

In [106]:
np.max(e,axis=0)

array([65., 67., 88.])

In [107]:
np.prod(e,axis=0)

array([ 66300.,   3618., 507496.])

In [108]:
np.mean(e)

53.111111111111114

In [109]:
np.mean(e,axis=1)

array([30.66666667, 68.66666667, 60.        ])

In [111]:
np.mean(e,axis=0)

array([47.33333333, 32.        , 80.        ])

In [112]:
np.median(e,axis=1)

array([17., 67., 65.])

In [114]:
np.median(e,axis=0)

array([60., 27., 79.])

In [116]:
np.std(e,axis=1)

array([30.55414138,  7.84573486, 25.15286597])

In [117]:
np.var(e,axis=1)

array([933.55555556,  61.55555556, 632.66666667])

In [119]:
np.sin(e)

array([[-0.96139749,  0.90929743, -0.67677196],
       [-0.30481062, -0.85551998, -0.44411267],
       [ 0.82682868,  0.95637593,  0.0353983 ]])

In [120]:
np.cos(e)

array([[-0.27516334, -0.41614684, -0.73619272],
       [-0.95241298, -0.5177698 , -0.89597095],
       [-0.56245385, -0.29213881,  0.99937328]])

In [121]:
np.tan(e)

array([[ 3.49391565, -2.18503986,  0.9192864 ],
       [ 0.32004039,  1.65231726,  0.49567753],
       [-1.47003826, -3.2737038 ,  0.0354205 ]])